services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: proxy
    volumes:
      - ./proxy.py:/app/main.py
    ports:
      - 5555:5555
      - 5556:5556

  publisher1: #nome qqr
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./publisher_dice.py:/app/main.py
    depends_on:
      - proxy
    deploy:
      replicas: 1

  publisher2: #nome qqr
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./publisher_time.py:/app/main.py
    depends_on:
      - proxy
    deploy:
      replicas: 1

  subscriber1: #nome qqr 
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./subscriber_dice.py:/app/main.py
    depends_on:
      - proxy
    deploy:
      replicas: 1

  subscriber2: #nome qqr 
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./subscriber_time.py:/app/main.py
    depends_on:
      - proxy
    deploy:
      replicas: 1

  subscriber3: #nome qqr 
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./subscriber_dice_time.py:/app/main.py
    depends_on:
      - proxy
    deploy:
      replicas: 1
