FROM python:3.13.7-alpine3.21

WORKDIR /app

RUN pip install grpcio grpcio-tools

COPY ./task_manager.proto .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. task_manager.proto

COPY ./requirements.txt /code/requirements.txt
#EXTRA: copia dependencias p rodar rest (add isso ^)

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
#EXTRA: copia dependencia p rodar rest (add isso^)

COPY ./cliente.py .
 
# codigo normal CMD ["python", "cliente.py"] 

CMD ["fastapi", "run", "cliente.py"] 
# extra add isso ^