services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile_servidor
    container_name: servidor
    ports:
     #normal - 50051:50051
     - 8000:8000

  cliente:
    build:
      context: .
      dockerfile: Dockerfile_cliente
    container_name: cliente
    depends_on:
      - servidor
